"""
Postgres Service Module for ChaloGhumo.

This module provides a lightweight interface for executing dynamically generated 
SQL queries against the relational destination database. It serves as a 
hard-constraint filter in the RAG pipeline.
"""

from typing import Any, List
from uuid import UUID

from sqlalchemy import text

from core.database import SessionLocal


class PostgresService:
    """
    Relational Data Access Layer.
    
    Responsible for executing filtered queries generated by the QueryBuilder.
    Provides candidate IDs that satisfy hard constraints (budget, location, etc.).
    """

    async def fetch_candidate_ids(self, sql_query: str) -> List[UUID]:
        """
        Executes a read-only SQL query to retrieve matching Destination IDs.
        
        Args:
            sql_query: The SQL SELECT statement generated by the LLM.
            
        Returns:
            A list of UUIDs for destinations matching the relational constraints.
        """
        try:
            db = SessionLocal()
            
            # 1. Security Guardrail: Enforce Read-Only Pattern
            # Prevents LLM-generated prompt injections from executing destructive SQL.
            stripped_query = sql_query.strip().upper()
            if not stripped_query.startswith("SELECT"):
                print(f"SECURITY ALERT: Blocked non-SELECT query: {sql_query}")
                return []
            
            # 2. Execution and Mapping
            result = db.execute(text(sql_query))
            ids = [row[0] for row in result]
            
            db.close()
            return ids
        except Exception as e:
            # Note: We return an empty list rather than raising to prevent pipeline stalling.
            print(f"Postgres Query Error: {e}")
            return []


# Singleton service instance
postgres_service = PostgresService()
